import { Feather } from '@expo/vector-icons';
import { useFocusEffect, useRouter } from 'expo-router';
import { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { getCurrentAdminAccess } from '@/lib/admin';
import { supabase } from '@/lib/supabase';
import { useAppTheme } from '@/providers/ThemeProvider';
import { useThemedStyles } from '@/theme/use-themed-styles';

type Setting={key:string;value:unknown;description:string;public_read:boolean;updated_at:string|null;updated_by:string|null};
type Flag={key:string;enabled:boolean;description:string;allowed_roles:string[];allowed_user_ids:string[];updated_at:string|null;updated_by:string|null};

function displayValue(value:unknown){if(typeof value==='string')return value;if(typeof value==='boolean'||typeof value==='number')return String(value);try{return JSON.stringify(value)}catch{return String(value)}}
function parseValue(input:string, original:unknown){if(typeof original==='boolean')return input.trim().toLowerCase()==='true';if(typeof original==='number'){const n=Number(input);if(Number.isNaN(n))throw new Error('Geçerli bir sayı gir.');return n}if(typeof original==='string')return input;try{return JSON.parse(input)}catch{throw new Error('Geçerli JSON gir.')}}

export default function AdminSystemScreen(){
 const router=useRouter();const styles=useThemedStyles(baseStyles);const{colors}=useAppTheme();
 const[loading,setLoading]=useState(true);const[saving,setSaving]=useState<string|null>(null);const[settings,setSettings]=useState<Setting[]>([]);const[flags,setFlags]=useState<Flag[]>([]);
 const[newFlagKey,setNewFlagKey]=useState('');const[newFlagDescription,setNewFlagDescription]=useState('');
 const[editingSetting,setEditingSetting]=useState<Setting|null>(null);const[editingText,setEditingText]=useState('');
 const load=useCallback(async()=>{setLoading(true);try{const access=await getCurrentAdminAccess();if(!access.canManageSystem){router.replace('/admin' as never);return}const[s,f]=await Promise.all([supabase.rpc('admin_list_system_settings'),supabase.rpc('admin_list_feature_flags')]);if(s.error)throw s.error;if(f.error)throw f.error;setSettings((s.data??[]) as Setting[]);setFlags((f.data??[]) as Flag[])}catch(error:any){Alert.alert('Hata',error?.message??'Sistem ayarları yüklenemedi.')}finally{setLoading(false)}},[router]);
 useFocusEffect(useCallback(()=>{void load()},[load]));
 const byKey=useMemo(()=>Object.fromEntries(settings.map(s=>[s.key,s])),[settings]);
 const quickKeys=['maintenance_mode','registration_enabled','community_creation_enabled','event_creation_enabled','force_update_enabled','follow_enabled'];
 const quickLabels:Record<string,string>={maintenance_mode:'Bakım modu',registration_enabled:'Yeni kayıtlar',community_creation_enabled:'Topluluk oluşturma',event_creation_enabled:'Etkinlik oluşturma',force_update_enabled:'Zorunlu güncelleme',follow_enabled:'Takip özelliği'};
 async function saveSetting(setting:Setting,nextValue:unknown){setSaving(setting.key);try{const{error}=await supabase.rpc('admin_set_system_setting',{p_key:setting.key,p_value:nextValue,p_description:setting.description,p_public_read:setting.public_read});if(error)throw error;setSettings(prev=>prev.map(s=>s.key===setting.key?{...s,value:nextValue}:s));setEditingSetting(null);setEditingText('')}catch(error:any){Alert.alert('Hata',error?.message??'Ayar kaydedilemedi.')}finally{setSaving(null)}}
 function editSetting(setting:Setting){setEditingSetting(setting);setEditingText(displayValue(setting.value))}
 async function saveEdited(){if(!editingSetting)return;try{await saveSetting(editingSetting,parseValue(editingText,editingSetting.value))}catch(error:any){Alert.alert('Hata',error?.message??'Geçersiz değer.')}}
 async function toggleFlag(flag:Flag){setSaving(`flag:${flag.key}`);try{const{error}=await supabase.rpc('admin_save_feature_flag',{p_key:flag.key,p_enabled:!flag.enabled,p_description:flag.description,p_allowed_roles:flag.allowed_roles,p_allowed_user_ids:flag.allowed_user_ids});if(error)throw error;setFlags(prev=>prev.map(f=>f.key===flag.key?{...f,enabled:!f.enabled}:f))}catch(error:any){Alert.alert('Hata',error?.message??'Feature flag güncellenemedi.')}finally{setSaving(null)}}
 async function createFlag(){const key=newFlagKey.trim();if(!key){Alert.alert('Eksik bilgi','Feature flag anahtarı gerekli.');return}setSaving('new-flag');try{const{error}=await supabase.rpc('admin_save_feature_flag',{p_key:key,p_enabled:false,p_description:newFlagDescription.trim(),p_allowed_roles:[],p_allowed_user_ids:[]});if(error)throw error;setNewFlagKey('');setNewFlagDescription('');await load()}catch(error:any){Alert.alert('Hata',error?.message??'Feature flag oluşturulamadı.')}finally{setSaving(null)}}
 function removeFlag(flag:Flag){Alert.alert('Feature flag silinsin mi?',flag.key,[{text:'Vazgeç',style:'cancel'},{text:'Sil',style:'destructive',onPress:async()=>{setSaving(`delete:${flag.key}`);try{const{error}=await supabase.rpc('admin_delete_feature_flag',{p_key:flag.key});if(error)throw error;setFlags(prev=>prev.filter(f=>f.key!==flag.key))}catch(error:any){Alert.alert('Hata',error?.message??'Feature flag silinemedi.')}finally{setSaving(null)}}}])}
 if(loading)return <View style={styles.centered}><ActivityIndicator color={colors.primary}/><Text style={styles.muted}>Sistem ayarları yükleniyor...</Text></View>;
 return <View style={styles.container}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.header}><Pressable style={styles.iconButton} onPress={()=>router.back()}><Feather name="chevron-left" size={24} color={colors.textPrimary}/></Pressable><View style={{flex:1}}><Text style={styles.eyebrow}>YÖNETİM</Text><Text style={styles.title}>Sistem</Text></View><Pressable style={styles.iconButton} onPress={()=>void load()}><Feather name="refresh-cw" size={18} color={colors.textSecondary}/></Pressable></View>
 <Text style={styles.sectionTitle}>Hızlı Kontroller</Text><View style={styles.card}>{quickKeys.map(key=>{const s=byKey[key];if(!s)return null;const enabled=Boolean(s.value);return <View key={key} style={styles.row}><View style={{flex:1}}><Text style={styles.rowTitle}>{quickLabels[key]}</Text><Text style={styles.rowSubtitle}>{s.description}</Text></View><Switch value={enabled} onValueChange={v=>void saveSetting(s,v)} disabled={saving===key}/></View>})}</View>
 <Text style={styles.sectionTitle}>Uygulama Ayarları</Text>{editingSetting?<View style={styles.editorCard}><Text style={styles.rowTitle}>{editingSetting.key}</Text><Text style={styles.rowSubtitle}>{editingSetting.description}</Text><TextInput value={editingText} onChangeText={setEditingText} multiline style={[styles.input,styles.editorInput]} placeholderTextColor="#666675"/><View style={styles.editorActions}><Pressable style={styles.cancelButton} onPress={()=>{setEditingSetting(null);setEditingText('')}}><Text style={styles.cancelText}>Vazgeç</Text></Pressable><Pressable style={styles.primaryButtonSmall} onPress={()=>void saveEdited()} disabled={saving===editingSetting.key}><Text style={styles.primaryButtonText}>Kaydet</Text></Pressable></View></View>:null}<View style={styles.card}>{settings.filter(s=>!quickKeys.includes(s.key)).map(s=><Pressable key={s.key} style={styles.settingRow} onPress={()=>editSetting(s)}><View style={{flex:1}}><Text style={styles.rowTitle}>{s.key}</Text><Text style={styles.settingValue}>{displayValue(s.value)}</Text><Text style={styles.rowSubtitle}>{s.description}</Text></View><Feather name="edit-2" size={17} color={colors.primary}/></Pressable>)}</View>
 <Text style={styles.sectionTitle}>Feature Flags</Text><View style={styles.form}><TextInput value={newFlagKey} onChangeText={setNewFlagKey} placeholder="örn. beta_reader" placeholderTextColor="#666675" autoCapitalize="none" style={styles.input}/><TextInput value={newFlagDescription} onChangeText={setNewFlagDescription} placeholder="Açıklama" placeholderTextColor="#666675" style={styles.input}/><Pressable style={styles.primaryButton} onPress={()=>void createFlag()} disabled={saving==='new-flag'}><Text style={styles.primaryButtonText}>Feature flag ekle</Text></Pressable></View>
 <View style={styles.card}>{flags.length===0?<Text style={styles.muted}>Henüz feature flag yok.</Text>:flags.map(flag=><View key={flag.key} style={styles.flagRow}><View style={{flex:1}}><Text style={styles.rowTitle}>{flag.key}</Text><Text style={styles.rowSubtitle}>{flag.description||'Açıklama yok'}</Text></View><Switch value={flag.enabled} onValueChange={()=>void toggleFlag(flag)} disabled={saving===`flag:${flag.key}`}/><Pressable onPress={()=>removeFlag(flag)} style={styles.deleteButton}><Feather name="trash-2" size={16} color="#F47A86"/></Pressable></View>)}</View>
 <Text style={styles.note}>Bu ekran yalnızca admin ve super_admin rollerine açıktır. Değişiklikler işlem geçmişine kaydedilir.</Text></ScrollView></View>
}
const baseStyles=StyleSheet.create({container:{flex:1,backgroundColor:'#0A0A0E'},content:{width:'100%',maxWidth:760,alignSelf:'center',padding:18,paddingBottom:48},centered:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#0A0A0E',padding:24},header:{flexDirection:'row',alignItems:'center',gap:12,marginBottom:22},iconButton:{width:42,height:42,borderRadius:13,alignItems:'center',justifyContent:'center',backgroundColor:'#15151D',borderWidth:1,borderColor:'#292934'},eyebrow:{fontSize:11,fontWeight:'900',letterSpacing:1.1,color:'#A985FF'},title:{fontSize:25,fontWeight:'900',color:'#F5F5F8'},sectionTitle:{fontSize:17,fontWeight:'800',color:'#F5F5F8',marginTop:10,marginBottom:10},card:{backgroundColor:'#15151D',borderWidth:1,borderColor:'#292934',borderRadius:17,padding:14,marginBottom:18},editorCard:{backgroundColor:'#15151D',borderWidth:1,borderColor:'#5A427C',borderRadius:17,padding:14,marginBottom:12},editorInput:{minHeight:70,textAlignVertical:'top',marginTop:10},editorActions:{flexDirection:'row',justifyContent:'flex-end',gap:8},cancelButton:{paddingHorizontal:14,paddingVertical:10,borderRadius:11,borderWidth:1,borderColor:'#30303D'},cancelText:{color:'#A5A5B3',fontWeight:'800'},primaryButtonSmall:{paddingHorizontal:14,paddingVertical:10,borderRadius:11,backgroundColor:'#6C3CC5'},row:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:11,borderBottomWidth:1,borderBottomColor:'#23232D'},settingRow:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:12,borderBottomWidth:1,borderBottomColor:'#23232D'},flagRow:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:11,borderBottomWidth:1,borderBottomColor:'#23232D'},rowTitle:{color:'#F5F5F8',fontSize:14,fontWeight:'800'},rowSubtitle:{color:'#8E8E9D',fontSize:12,lineHeight:17,marginTop:3},settingValue:{color:'#A985FF',fontSize:13,fontWeight:'800',marginTop:4},form:{gap:9,marginBottom:12},input:{backgroundColor:'#15151D',borderWidth:1,borderColor:'#30303D',borderRadius:13,color:'#F5F5F8',paddingHorizontal:13,paddingVertical:11},primaryButton:{backgroundColor:'#6C3CC5',borderRadius:13,paddingVertical:12,alignItems:'center'},primaryButtonText:{color:'#fff',fontWeight:'900'},deleteButton:{width:34,height:34,borderRadius:10,alignItems:'center',justifyContent:'center',backgroundColor:'#2A171D'},muted:{color:'#8E8E9D',marginTop:10},note:{color:'#747483',fontSize:12,lineHeight:18,textAlign:'center',marginTop:4}});
