begin;

create table if not exists public.product_analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_name text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint product_analytics_event_name_check check (
    event_name in ('app_open','onboarding_completed','book_opened','shelf_updated','content_created')
  ),
  constraint product_analytics_metadata_object_check check (jsonb_typeof(metadata) = 'object')
);

create index if not exists product_analytics_events_user_created_idx
  on public.product_analytics_events(user_id, created_at desc);
create index if not exists product_analytics_events_name_created_idx
  on public.product_analytics_events(event_name, created_at desc);

alter table public.product_analytics_events enable row level security;

revoke all on public.product_analytics_events from anon, authenticated;

drop function if exists public.track_product_event(text, jsonb);
create function public.track_product_event(p_event_name text, p_metadata jsonb default '{}'::jsonb)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_metadata jsonb := coalesce(p_metadata, '{}'::jsonb);
begin
  if v_user_id is null then
    return;
  end if;

  if p_event_name not in ('app_open','onboarding_completed','book_opened','shelf_updated','content_created') then
    raise exception 'Unsupported analytics event';
  end if;

  if jsonb_typeof(v_metadata) <> 'object' then
    raise exception 'Analytics metadata must be an object';
  end if;

  -- Keep analytics intentionally low-cardinality and privacy-safe.
  v_metadata := v_metadata - 'email' - 'username' - 'text' - 'title' - 'query' - 'message' - 'description' - 'token';

  insert into public.product_analytics_events(user_id, event_name, metadata)
  values (v_user_id, p_event_name, v_metadata);
end;
$$;

revoke all on function public.track_product_event(text, jsonb) from public;
grant execute on function public.track_product_event(text, jsonb) to authenticated;

create or replace function public.capture_shelf_analytics()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.product_analytics_events(user_id, event_name, metadata)
  values (
    new.user_id,
    'shelf_updated',
    jsonb_build_object('status', new.status)
  );
  return new;
end;
$$;

create or replace function public.capture_content_analytics()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.product_analytics_events(user_id, event_name, metadata)
  values (
    new.user_id,
    'content_created',
    jsonb_build_object('content_type', tg_table_name)
  );
  return new;
end;
$$;

drop trigger if exists product_analytics_shelf on public.user_book_status;
create trigger product_analytics_shelf
after insert or update of status on public.user_book_status
for each row execute function public.capture_shelf_analytics();

drop trigger if exists product_analytics_post_created on public.posts;
create trigger product_analytics_post_created
after insert on public.posts
for each row execute function public.capture_content_analytics();

drop trigger if exists product_analytics_review_created on public.reviews;
create trigger product_analytics_review_created
after insert on public.reviews
for each row execute function public.capture_content_analytics();

drop trigger if exists product_analytics_quote_created on public.quotes;
create trigger product_analytics_quote_created
after insert on public.quotes
for each row execute function public.capture_content_analytics();

commit;
