begin;

create table if not exists public.premium_analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  entitlement_id uuid references public.premium_entitlements(id) on delete set null,
  event_type text not null check (
    event_type in (
      'entitlement_created',
      'status_changed',
      'expiration_changed',
      'renewal_state_changed',
      'source_state_changed'
    )
  ),
  source text not null check (source in ('apple','google','admin_grant')),
  status text not null check (
    status in ('inactive','active','trialing','grace_period','expired','revoked')
  ),
  previous_status text,
  product_id text,
  will_renew boolean,
  expires_at timestamptz,
  provider_event_type text,
  created_at timestamptz not null default now()
);

create index if not exists premium_analytics_events_created_idx
  on public.premium_analytics_events(created_at desc);

create index if not exists premium_analytics_events_user_created_idx
  on public.premium_analytics_events(user_id, created_at desc);

create index if not exists premium_analytics_events_source_status_idx
  on public.premium_analytics_events(source, status, created_at desc);

alter table public.premium_analytics_events enable row level security;

revoke all on table public.premium_analytics_events from public, anon, authenticated;

create or replace function public.capture_premium_analytics_event()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_event_type text;
begin
  if tg_op = 'INSERT' then
    v_event_type := 'entitlement_created';
  elsif new.status is distinct from old.status then
    v_event_type := 'status_changed';
  elsif new.expires_at is distinct from old.expires_at then
    v_event_type := 'expiration_changed';
  elsif new.will_renew is distinct from old.will_renew then
    v_event_type := 'renewal_state_changed';
  elsif new.provider_event_type is distinct from old.provider_event_type then
    v_event_type := 'source_state_changed';
  else
    return new;
  end if;

  insert into public.premium_analytics_events (
    user_id,
    entitlement_id,
    event_type,
    source,
    status,
    previous_status,
    product_id,
    will_renew,
    expires_at,
    provider_event_type
  )
  values (
    new.user_id,
    new.id,
    v_event_type,
    new.source,
    new.status,
    case when tg_op = 'UPDATE' then old.status else null end,
    new.product_id,
    new.will_renew,
    new.expires_at,
    new.provider_event_type
  );

  return new;
end;
$$;

revoke all on function public.capture_premium_analytics_event()
from public, anon, authenticated;

drop trigger if exists premium_entitlements_capture_analytics
on public.premium_entitlements;

create trigger premium_entitlements_capture_analytics
after insert or update
on public.premium_entitlements
for each row
execute function public.capture_premium_analytics_event();

create or replace function public.admin_premium_analytics_overview()
returns table (
  active_premium_users bigint,
  active_paid_users bigint,
  active_admin_grant_users bigint,
  apple_active_users bigint,
  google_active_users bigint,
  trialing_users bigint,
  grace_period_users bigint,
  expiring_7d_users bigint,
  non_renewing_paid_users bigint,
  premium_events_7d bigint,
  premium_events_30d bigint
)
language sql
security definer
set search_path = ''
as $$
  with active as (
    select pe.*
    from public.premium_entitlements pe
    where pe.status in ('active','trialing','grace_period')
      and pe.revoked_at is null
      and pe.starts_at <= now()
      and (pe.expires_at is null or pe.expires_at > now())
  )
  select
    (select count(distinct user_id) from active),
    (select count(distinct user_id) from active where source in ('apple','google')),
    (select count(distinct user_id) from active where source = 'admin_grant'),
    (select count(distinct user_id) from active where source = 'apple'),
    (select count(distinct user_id) from active where source = 'google'),
    (select count(distinct user_id) from active where status = 'trialing'),
    (select count(distinct user_id) from active where status = 'grace_period'),
    (select count(distinct user_id) from active where expires_at is not null and expires_at <= now() + interval '7 days'),
    (select count(distinct user_id) from active where source in ('apple','google') and will_renew is false),
    (select count(*) from public.premium_analytics_events where created_at >= now() - interval '7 days'),
    (select count(*) from public.premium_analytics_events where created_at >= now() - interval '30 days')
  where public.has_admin_role(array['admin','super_admin']);
$$;

revoke all on function public.admin_premium_analytics_overview()
from public, anon;

grant execute on function public.admin_premium_analytics_overview()
to authenticated;

create or replace function public.admin_premium_analytics_daily(
  p_days integer default 30
)
returns table (
  day date,
  entitlement_created bigint,
  status_changed bigint,
  expiration_changed bigint,
  renewal_state_changed bigint,
  source_state_changed bigint
)
language sql
security definer
set search_path = ''
as $$
  with days as (
    select generate_series(
      current_date - (greatest(1, least(coalesce(p_days,30), 180)) - 1),
      current_date,
      interval '1 day'
    )::date as day
  )
  select
    d.day,
    count(*) filter (where e.event_type = 'entitlement_created'),
    count(*) filter (where e.event_type = 'status_changed'),
    count(*) filter (where e.event_type = 'expiration_changed'),
    count(*) filter (where e.event_type = 'renewal_state_changed'),
    count(*) filter (where e.event_type = 'source_state_changed')
  from days d
  left join public.premium_analytics_events e
    on e.created_at >= d.day
   and e.created_at < d.day + interval '1 day'
  where public.has_admin_role(array['admin','super_admin'])
  group by d.day
  order by d.day;
$$;

revoke all on function public.admin_premium_analytics_daily(integer)
from public, anon;

grant execute on function public.admin_premium_analytics_daily(integer)
to authenticated;

comment on table public.premium_analytics_events is
'Internal server-generated Premium lifecycle analytics. Clients cannot write or read this table directly.';

commit;
